version: 0.2

phases:
  install:
    commands:
      - echo Installing Ansible
      - pip install ansible

  pre_build:
    commands:
      - echo Checking version
      - ansible --version
      - chmod 400 ansiblepvt.key

  build:
    commands:
      - echo Testing connectivity
      - ansible all -i inventory -m ping --private-key ansiblepvt.key
      - echo Running playbook
      - ansible-playbook site.yml
  
  artifacts:
  files:
    - '**/*'
