# aws_ec2.yml
plugin: aws_ec2
regions:
  - us-west-1
filters:
  tag:Name: MyAppServer
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
groups:
  dev: "'MyAppServer' in tags.Name"
